### ISSUE TITLE
skygear-server-build-from-binary-file 

### ISSUE THREAD

**Issue by KhaledAld** [SkygearIO/chat#228] opened 2018-09-30 14:06 UTC
https://discuss.skygear.io/t/skygear-server-build-from-binary-file/172

**Comment by tensiuyan** [comment] 2018-10-23 07:38
@KhaledAld Hello! Closing this issue since this is not a bug report. Please reach us over https://discuss.skygear.io for support.

**Closed by tensiuyan** 2018-10-23 07:38 UTC
